TRUNCATE TABLE privilege;
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('viewRestaurant','View Restaurant','/view-restaurant','GET','management','frontend', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method,is_deleted) VALUES('registerRestaurant','Register Restaurant','/register-restaurant','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editRestaurant','Edit Restaurant','/edit-restaurant/{restaurantId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('viewMacAddress','view Mac Addresst','/view-mac-address/{restaurantId}','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('viewContact','View Contact','/view-contact','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editContact','Edit Contact','/edit-contact/{contactId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editChain','Edit Chain','/edit-chain/{chainId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('viewChain','View Chain','/view-chain','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('addChain','Add Chain','/add-chain','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('viewUser','View User','/view-user','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('updateUser','Update User','/update-user/{userId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('registerUser','Register User','/add-user','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('userProfile','User Profile','/userProfile','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('fetchRolesForPermission','Fetch Roles For Permission','/fetch-roles-for-permission','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('permission','Permission','/permission/{roleId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('viewRoles','View Roles','/view-roles','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('addRole','Add Role','/add-role','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editRole','Edit Role','/edit-role/{roleId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('viewPrivileges','View Privileges','/view-privileges','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('addPrivilege','Add Privilege','/add-privilege','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editPrivilege','Edit Privilege','/edit-privilege/{privilegeId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('roleAssign','Role Assign','/assign-role/{userId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('rolesList','Roles List','/roles','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('addRole','Add Role','/roles','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editRole','Edit Role','/roles/{roleId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('roleDetail','Role Detail','/roles/{roleId}','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('deleteRole','Delete Role','/roles/{roleId}','DELETE', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('usersList','Users List','/user','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('addUser','Add User','/auth/signup','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editUser','Edit User','/user/{id}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('changeUserStatus','Change User Status','/user/changestatus/{id}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('userProfile','User Profile','/user/uploadprofile','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('deleteUser','Delete User','/user/{id}','DELETE', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('addUserRole','Add User Role','/user-role','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editUserRole','Edit User Role','/user-role/{userRoleId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('deleteUserRole','Delete User Role','/user-role/{userRoleId}','DELETE', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('userRolesList','User Roles List','/user-role/assigned-roles/{userId}','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('addRolePrivilege','Add Role Privilege','/role-privilege','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editRolePrivilege','Edit Role Privilege','/role-privilege/{rolePrivilegeId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('deleteRolePrivilege','Delete Role Privilege','/role-privilege/{rolePrivilegeId}','DELETE', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('privilegesOfRolesList','Privileges Of Roles List','/role-privilege/{roleId}','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('addRestaurant','Add Restaurant','/restaurant','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editRestaurant','Edit Restaurant','/restaurant/{restaurantId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('restaurantList','Restaurant List','/restaurant','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('restaurantDetail','Restaurant Detail','/restaurant/{restaurantId}','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('deleteRestaurant','Delete Restaurant','/restaurant/{restaurantId}','DELETE', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('resetLicenseKey','Reset License Key','/restaurant/reset-license-key/{restaurantId}','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('uploadLogoOfRestaurant','Upload Logo Of Restaurant','/restaurant/upload-logo/{restaurantId}','DELETE', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('addPrivilege','Add Privilege','/privileges','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editPrivilege','Edit Privilege','/privileges/{privilegeId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('privilegesList','Privileges List','/privileges','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('privilegeDetail','Privilege Detail','/privileges/{privilegeId}','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('deletePrivilege','Delete Privilege','/privileges/{privilegeId}','DELETE', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('addContact','Add Contact','/contact','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editContact','Edit Contact','/contact/{contactId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('contactsList','Contacts List','/contact','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('contactDetail','Contact Detail','/contact/{contactId}','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('deleteContact','Delete Contact','/contact/{contactId}','DELETE', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('addChain','Add Chain','/chain','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('editChain','Edit Chain','/chain/{chainId}','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('chainsList','Chains List','/chain','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('chainDetail','Chain Detail','/chain/{chainId}','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('deleteChain','Delete Chain','/chain/{chainId}','DELETE', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('login','Login','/auth/login','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('signup','Signup','/auth/signup','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('changePassword','Change Password','/auth/changepassword','PUT', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('emailVerification','Emai Verification','/verify/account/{emailVerificationToken}','GET', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('sendVerificationToken','Send Verification Token','/verify/resend/{email}','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('resetPassword','Reset Password','/verify/sendpasswordresetcode/{email}','POST', 0);
INSERT IGNORE INTO privilege(privilege_name,privilege_description,privilege_url,method, is_deleted) VALUES('checkResetcode','Check Resetcode','/verify/checkresetcode','GET', 0);
